/*
-- Query: SELECT * FROM juego.cartas
LIMIT 0, 1000

-- Date: 2019-05-23 17:46
*/
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (1,'Productor','azul',0,0,0,0,2,1,1,2,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_astroport.PNG?alt=media&token=36097410-e3c5-48fc-a9f6-f54cc09215e7',0,2,'cafe',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (2,'Investigacion','blanco',0,0,0,1,2,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_banqueInterstellaire.PNG?alt=media&token=dc3b74c7-e125-4eaa-b12d-98267606cc05',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (3,'Investigacion','blanco',1,0,0,1,1,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_corpsExpeditionnaire.PNG?alt=media&token=febf8ee9-1117-483a-ae38-149332e21aa8',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (4,'Investigacion','blanco',0,0,1,0,1,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_creditsALInvestissement.PNG?alt=media&token=7eb3cb53-42d4-4a38-bbf3-a0af3b0ab6fa',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (5,'Investigacion','blanco',0,0,-2,0,6,2,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_federationGalactique.PNG?alt=media&token=d4f7a04f-237c-46b3-9a4b-d5b8d43f285d',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (6,'Mixta','amarillo',3,0,0,0,6,4,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_flotteAlien.PNG?alt=media&token=2eeec6d0-39a3-4e05-9548-04f056c32100',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (7,'Investigacion','amarillo',0,0,0,1,4,2,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_laboratoiresDeRecherche.PNG?alt=media&token=c1f90e61-1504-4b10-8452-0c99cba56a27',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (8,'Productor','azul',0,0,0,0,2,1,1,2,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_mondeProducteur.PNG?alt=media&token=fea86e2e-04ce-400a-95ab-117fd1be056c',0,2,'azul',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (9,'Militar','blanco',2,0,0,0,2,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_nouvelleSparte.PNG?alt=media&token=69733bf0-2cf4-42ea-84bd-af0cad1161d7',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (10,'Investigacion','blanco',2,0,0,0,6,5,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_nouvelOrdreGalactique.PNG?alt=media&token=b769597e-dfca-45bd-b48a-c5acc1675f52',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (11,'Investigacion','blanco',0,0,0,1,1,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_travauxPublics.PNG?alt=media&token=75955216-b804-438d-9d9f-718654b86c9a',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (12,'Planeta','blanco',0,0,0,0,4,3,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_baseAlien.PNG?alt=media&token=e8043c56-7226-408b-8deb-f856652f026f',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (13,'Mixta','blanco',0,0,0,0,1,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_cacheDeFuel.PNG?alt=media&token=11f79df5-ab76-4786-9b6b-cb5e927f13cf',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (14,'Planeta','blanco',0,0,0,0,2,1,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_ceinture.PNG?alt=media&token=9b7b0802-6e03-4dc0-b1e9-55c61649e182',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (15,'Investigacion','blanco',-1,0,0,0,6,5,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_liguePanGalactique.PNG?alt=media&token=a129d37b-912f-4966-b98f-309ff07f264b',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (16,'Mixta','blanco',0,0,0,0,2,2,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_raceAquatique.PNG?alt=media&token=3e43609a-6fd9-4712-b6e3-bb32d49ce180',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (17,'Mixta','blanco',0,0,0,0,2,2,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_raceReptiliene.PNG?alt=media&token=cf37dbf7-505b-4dba-a5fc-c3e1ee3c232f',0,0,'blanco',0);
INSERT INTO `cartas` (`idcartas`,`tipo`,`colorPago`,`poderMilitar`,`costoMilitar`,`costoInvestigacion`,`bonusExploracion`,`sacrificio`,`puntosIntangibles`,`pago`,`pBonusCarta`,`url`,`costoPlanetas`,`pagoCarta`,`pagoColor`,`produccion`) VALUES (18,'Mixta','blanco',3,0,0,0,6,4,0,0,'https://firebasestorage.googleapis.com/v0/b/arquitectura-92cab.appspot.com/o/card_FlotteAlienPerdue.png?alt=media&token=fc5cfa24-2211-4a43-9e0c-44e51a604a93',NULL,0,'blanco',0);
